# Generated by Django 5.0.4 on 2024-04-04 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('date_registration', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
